#!/bin/bash

set -euo pipefail  # Exit on error, undefined vars, pipe failures
IFS=$'\n\t'        # Safer field splitting

ORIGINAL_DIR="$(pwd)"

# === Error Handling ===
cleanup() {
    local exit_code=$?

    # Capture ERR context if available
    if [[ ${__err_line:-} ]]; then
        echo "ERROR at line $__err_line: $__err_command failed" >&2
    fi

    if [ $exit_code -ne 0 ]; then
        echo "" >&2
        echo "====================================" >&2
        echo "Script failed - returning to $ORIGINAL_DIR" >&2
        echo "====================================" >&2
    fi

    cd "$ORIGINAL_DIR" 2>/dev/null || true
    exit $exit_code
}

# Store ERR context for cleanup
trap '__err_line=$LINENO; __err_command=$BASH_COMMAND' ERR
trap cleanup EXIT

VERBOSE="${VERBOSE:-0}"
DEBUG="${DEBUG:-0}"

[ "$VERBOSE" = "1" ] && set -x

cd "$(dirname "${BASH_SOURCE[0]}")"

base_dir=$(basename "$0" .sh)

# Array with directory names
directories=("inc" "src" "MDK-ARM")
op_counter=0

check_dependencies() {
    local missing=()

    for cmd in curl arm-none-eabi-gcc make; do
        if ! command -v "$cmd" &>/dev/null; then
            missing+=("$cmd")
        fi
    done

    if [ ${#missing[@]} -gt 0 ]; then
        echo "Error: Missing required tools: ${missing[*]}" >&2
        echo "" >&2
        echo "Installation instructions:" >&2
        echo "  Debian/Ubuntu: sudo apt-get install ${missing[*]}" >&2
        echo "  Red Hat/CentOS: sudo yum install ${missing[*]}" >&2
        exit 1
    fi
}

press_any_key() {
    echo -n "Press any key to continue..."
    # read one character of input and discard it
    read -n 1 -s -r || true
    echo ""
}

check_dependencies

# Function to check for the existence of a directory and create it if it doesn't exist
create_directory() {
    local dir="$1"
    if [ ! -d "$dir" ]; then
        if mkdir "$dir"; then
            ((++op_counter))
            echo "Directory $dir created."
        else
            echo "Error: Failed to create directory $dir" >&2
            exit 1
        fi
    fi
}

# Create directories
create_directory "$base_dir" && cd "$base_dir"

for dir in "${directories[@]}"
do
  create_directory "$dir"
done

cd "${directories[0]}"

PY_GEN="$(realpath "${PY_GEN:-../../..}")"

if [ -e stm32g431xx.h ]; then
    # File exists
    opt=-l
else
    # File does not exist
    opt=-s
fi

py_name=''

# Detect Python
case $(uname -s | tr '[:upper:]' '[:lower:]') in
    linux*|darwin*)  py_name='python3' ;;
    *)               py_name='python' ;;  # Windows and others
esac

# Verify Python works
if ! command -v "$py_name" &>/dev/null; then
    echo "Error: $py_name not found" >&2
    exit 1
fi

force_inline=--force-inline
func_name=init_systick
PY_GEN_PY="$PY_GEN"
if command -v cygpath &>/dev/null; then
    py_path="$(command -v "$py_name")"
    case "$py_path" in
        /usr/bin/*|/bin/*) ;;  # Cygwin Python — keep cygwin path
        *) PY_GEN_PY="$(cygpath -w "$PY_GEN")" ;;  # Windows Python — convert
    esac
fi
py_gen=("$py_name" "$PY_GEN_PY/stm32cgen.py")

# Validate stm32cgen.py exists and is readable
if [ ! -f "$PY_GEN/stm32cgen.py" ]; then
    echo "Error: stm32cgen.py not found at $PY_GEN" >&2
    echo "Current PY_GEN=$PY_GEN" >&2
    exit 1
fi

generate_header() {
    local output_file="$1"
    shift  # Remove first argument

    if "${py_gen[@]}" "$@" > "$output_file"; then
        echo "File $output_file created."
        ((++op_counter))
    else
        echo "Error: Failed to generate $output_file" >&2
        exit 1
    fi
}

# Function to write a file only if it does not yet exist (preserves user edits)
create_file() {
    local filename="$1"
    if [ ! -f "$filename" ]; then
        cat > "$filename"
        if [ -s "$filename" ]; then
            ((++op_counter))
            echo "File $filename created."
        else
            echo "Error: $filename is empty after creation" >&2
            rm -f "$filename"
            return 1
        fi
    fi
}

# --------------------------------------------------------------------------- #
#  main.h  — generated by stm32cgen (-M).  G4 @ 170 MHz, SysTick IRQ enabled   #
#  so a real 1 ms time base (uptime()) is available for the blink loop.        #
# --------------------------------------------------------------------------- #
generate_header "main.h" $opt g431cb -M\
    -D NO                     0\
       NONE                   NO\
       OFF                    NO\
       YES                    \(\!NO\)\
       ON                     YES\
       ""\
       HCLK                   "170  /* 8 to 170 (MHz) */"\
       ""\
       SYSTICK_CLOCK_SOURCE   "0    /* 0 = HCLK / 8; 1 = HCLK         */"\
       SYSTICK_ENABLE         YES\
       SYSTICK_IRQ_ENABLE     YES\
    \
    -H "#if HCLK < 8 || HCLK > 170"\
    -H "  #error \"HCLK must be between 8 and 170 MHz\""\
    -H \#endif\
    \
    $force_inline\
    --post-init $func_name\
    -F ""\
    -F "__STATIC_FORCEINLINE void $func_name(void) {"\
    -F "  /* 1 ms SysTick from HCLK; IRQ enabled so uptime() advances. */"\
    -F "  /* LOAD uses SystemCoreClock, which init_rcc() sets to 170 MHz. */"\
    -F ""\
    -F "  SysTick->LOAD = (SystemCoreClock / (8 - SYSTICK_CLOCK_SOURCE * 7)) / 1000 - 1;"\
    -F "  SysTick->VAL  = SysTick->LOAD;"\
    -F "  SysTick->CTRL = SYSTICK_ENABLE * SysTick_CTRL_ENABLE_Msk"\
    -F "                  | SYSTICK_IRQ_ENABLE * SysTick_CTRL_TICKINT_Msk;"\
    -F "} /* $func_name() */"\
    -F ""\
    -F ""\
    -F "__STATIC_FORCEINLINE void idle(void); // {"\
    -F "  /* Routine to handle idle state (waiting for an event) */"\
    -F ""\
    -F "//} /* idle() */"\
    -F ""\
    -F ""\
    -F "__STATIC_FORCEINLINE unsigned process(void); // {"\
    -F "  /* Routine to perform main loop operations */"\
    -F ""\
    -F "//} /* process() */"\
    -F ""\
    -F "#if YES == SYSTICK_IRQ_ENABLE"\
    -F "  #define __SYSTICK_VOLATILE volatile"\
    -F "#else"\
    -F "  #define __SYSTICK_VOLATILE"\
    -F "#endif"\
    -F ""\
    -F "#if defined(__GNUC__) && ! defined(__clang__)" \
    -F "  __attribute__((used)) int _close(int fd)                          { (void)fd; return -1; }" \
    -F "  __attribute__((used)) int _lseek(int fd, int offset, int whence)  { (void)fd; (void)offset; (void)whence; return -1; }" \
    -F "  __attribute__((used)) int _read(int fd, char *buf, int len)       { (void)fd; (void)buf; (void)len; return -1; }" \
    -F "  __attribute__((used)) int _write(int fd, const char *buf, int len) { (void)fd; (void)buf; (void)len; return -1; }" \
    -F \#endif

# --------------------------------------------------------------------------- #
#  rcc.h  — hand-written G4 clock + PLL + flash configuration.                 #
#  G4 is a single-PLL (F4-style) part: HSE 8 MHz -> PLL (M=2,N=85,R=2) ->     #
#  170 MHz.  Range-1 *boost* mode (PWR_CR5.R1MODE cleared) is required to      #
#  exceed 150 MHz, and the flash needs 4 wait states at 170 MHz.               #
# --------------------------------------------------------------------------- #
create_file "rcc.h" << 'EOF'
#ifndef __RCC_H__
#define __RCC_H__

#include "stm32g431xx.h"

/* The G4 device header does not pull in the generic register-access helpers
 * (they live in the family header stm32g4xx.h, which also drags in the HAL).
 * Define the minimal CMSIS helpers locally, guarded so they are not redefined
 * if a future header provides them. */
#ifndef WRITE_REG
  #define WRITE_REG(REG, VAL)   ((REG) = (VAL))
#endif
#ifndef READ_REG
  #define READ_REG(REG)         ((REG))
#endif
#ifndef MODIFY_REG
  #define MODIFY_REG(REG, CLEARMASK, SETMASK) \
          WRITE_REG((REG), (((READ_REG(REG)) & (~(CLEARMASK))) | (SETMASK)))
#endif
#ifndef SET_BIT
  #define SET_BIT(REG, BIT)     ((REG) |= (BIT))
#endif
#ifndef CLEAR_BIT
  #define CLEAR_BIT(REG, BIT)   ((REG) &= ~(BIT))
#endif

/* G4 @ 170 MHz from an 8 MHz HSE crystal:
 *
 *   HSE            =  8 MHz
 *   PLL input      =  HSE / PLLM(2)       =  4 MHz   (must be 4..16 MHz)
 *   VCO frequency  =  4 MHz * PLLN(85)    = 340 MHz   (must be 128..344 MHz)
 *   PLLR output    = 340 MHz / 2          = 170 MHz   (PLLR field = 0 -> /2; max 170 MHz)
 *
 * The core must run in Voltage Scale 1 *boost* mode (PWR_CR5.R1MODE cleared)
 * to exceed 150 MHz, and the flash needs 4 wait states at 170 MHz.
 */

__STATIC_FORCEINLINE void configure_flash(void) {
  /* Enable the PWR peripheral clock (APB1). */
  RCC->APB1ENR1 |= RCC_APB1ENR1_PWREN;

  /* Voltage Scale 1 (Range 1, highest performance); clear R1MODE to enter
   * boost mode, which is required to run the core above 150 MHz. */
  MODIFY_REG(PWR->CR1, PWR_CR1_VOS, PWR_CR1_VOS_0);
  CLEAR_BIT(PWR->CR5, PWR_CR5_R1MODE);

  /* Flash: 4 wait states + prefetch + instruction/data caches. */
  MODIFY_REG(FLASH->ACR, FLASH_ACR_LATENCY,
             FLASH_ACR_LATENCY_4WS | FLASH_ACR_PRFTEN | FLASH_ACR_ICEN | FLASH_ACR_DCEN);
}

__STATIC_FORCEINLINE void init_rcc(void) {
  configure_flash();

  /* 1. Make sure we are on HSI while reconfiguring the PLL. */
  MODIFY_REG(RCC->CFGR, RCC_CFGR_SW, RCC_CFGR_SW_HSI);
  while ((RCC->CFGR & RCC_CFGR_SWS) != RCC_CFGR_SWS_HSI) {}
  CLEAR_BIT(RCC->CR, RCC_CR_PLLON);
  while (RCC->CR & RCC_CR_PLLRDY) {}

  /* 2. Start the 8 MHz HSE and wait for it to become stable. */
  SET_BIT(RCC->CR, RCC_CR_HSEON);
  while (!(RCC->CR & RCC_CR_HSERDY)) {}

  /* 3. Configure the PLL: source = HSE, M = 2, N = 85, R = 2, enable R output. */
  RCC->PLLCFGR =
      RCC_PLLCFGR_PLLSRC_HSE
    | RCC_PLLCFGR_PLLREN
    | ((2UL - 1UL) << RCC_PLLCFGR_PLLM_Pos)
    | (85UL        << RCC_PLLCFGR_PLLN_Pos)
    | (0UL        << RCC_PLLCFGR_PLLR_Pos);

  /* 4. Enable the PLL and wait for lock. */
  SET_BIT(RCC->CR, RCC_CR_PLLON);
  while (!(RCC->CR & RCC_CR_PLLRDY)) {}

  /* 5. Bus prescalers: AHB = /1, APB1 = /2, APB2 = /2. */
  RCC->CFGR |= RCC_CFGR_HPRE_DIV1 | RCC_CFGR_PPRE1_DIV2 | RCC_CFGR_PPRE2_DIV2;

  /* 6. Switch the system clock to the PLL output. */
  MODIFY_REG(RCC->CFGR, RCC_CFGR_SW, RCC_CFGR_SW_PLL);
  while ((RCC->CFGR & RCC_CFGR_SWS) != RCC_CFGR_SWS_PLL) {}

  /* Enable the GPIOC clock (LED on PC6) before init_gpio() configures pins. */
  RCC->AHB2ENR |= RCC_AHB2ENR_GPIOCEN;

  /* PLL output verified at 170 MHz for this board. */
  SystemCoreClock = 170000000u;
}

#endif /* __RCC_H__ */
EOF

# --------------------------------------------------------------------------- #
#  gpio.h  — generated by stm32cgen.  G4 register bit naming (GPIO_MODER_MODE  #
#  and GPIO_OSPEEDR_OSPEED) is used; PC6 is the LED output.                    #
# --------------------------------------------------------------------------- #
generate_header "gpio.h" -l g431cb -p GPIOC -m gpio -f init_gpio\
    --exclude-register IDR LCKR\
    -D USE_ANALOG_MODE_FOR_ALL_PINS_BY_DEFAULT 1\
       ""\
       GPIO_MODE "(USE_ANALOG_MODE_FOR_ALL_PINS_BY_DEFAULT * UINT32_MAX)"\
       PIN_XOR "(GPIO_MODE & 3UL)"\
       ""\
       PIN_MODE_INPUT "(0x00UL ^ PIN_XOR)"\
       PIN_MODE_OUTPUT "(0x01UL ^ PIN_XOR)"\
       PIN_MODE_AF "(0x02UL ^ PIN_XOR)"\
       PIN_MODE_ANALOG "(0x03UL ^ PIN_XOR)"\
       ""\
       "PIN_CFG(PIN, MODE)" "((MODE)   << ((PIN) * 2))"\
       "PIN_MODE(PIN, MODE)" "(((MODE)  << GPIO_MODER_MODE ## PIN ## _Pos) & GPIO_MODER_MODE ## PIN ## _Msk)"\
       "PIN_SPEED(PIN, SPEED)" "(((SPEED) << GPIO_OSPEEDR_OSPEED ## PIN ## _Pos) & GPIO_OSPEEDR_OSPEED ## PIN ## _Msk)"\
       "PIN_OTYPE(PIN, OTYPE)" "((OTYPE)   ? GPIO_OTYPER_OT ## PIN : 0)"\
       "PIN_PUPD(PIN, PUPD)" "(((PUPD)  << GPIO_PUPDR_PUPD ## PIN ## _Pos) & GPIO_PUPDR_PUPD ## PIN ## _Msk)"\
       "PIN_AF(PIN, AF)" "(AF << (PIN * 4))"\
       ""\
       GPIOC_MODE "( PIN_MODE(6, PIN_MODE_OUTPUT) /* PC6 -- LED */ )"\
       GPIOC_OTYPE "( 0 )"\
       GPIOC_OSPEED "( PIN_SPEED(6, PIN_SPEED_HIGH) /* PC6 -- high speed */ )"\
       GPIOC_PUPD "( 0 )"\
       ""\
       GPIOC_MODER "(GPIO_MODE ^ (GPIOC_MODE))"\
       GPIOC_OTYPER "(GPIOC_OTYPE)"\
       GPIOC_OSPEEDR "(GPIOC_OSPEED)"\
       GPIOC_PUPDR "(GPIOC_PUPD)"\
    \
    $force_inline\
    --no-def

cd ..

# Create main.c file in src directory from embedded data using Here Document
main_c_file="${directories[1]}/main.c"
if [ ! -f "$main_c_file" ]; then
  op_counter=$((op_counter + 1))
  cat << 'EOF' > "$main_c_file"
#include "main.h"

/* WeAct Studio STM32G431CBU6: a green LED is wired to PC6 (active HIGH).
 * The loop below blinks it at ~1 Hz using bit 9 of the 1 ms uptime counter
 * (same scheme as the F1/F4 reference demos: bit 9 flips every 512 ms, so the
 * LED period is 1024 ms ~= 1 Hz). */

static volatile uint64_t g_ticks;

void SysTick_Handler(void) {
  g_ticks++;
}

uint64_t uptime(void) {
  return g_ticks;
}

int main(void) {
  /* init() performs: init_rcc() -> init_gpio() -> init_systick(). */
  for (init(); process(); idle());
}

unsigned process(void) {
  /* Blink at ~1 Hz: bit 9 of the 1 ms uptime counter toggles every 512 ms,
   * so the LED is on for 512 ms and off for 512 ms (period ~1024 ms). */
  if (uptime() & (1ULL << 9)) {
    GPIOC->BSRR = GPIO_BSRR_BS6;       /* PC6 high -> LED on  */
  } else {
    GPIOC->BSRR = GPIO_BSRR_BR6;       /* PC6 low  -> LED off */
  }

  return !0;  /* Always continue loop */
}

void idle(void) {
  __WFI();
}
EOF
  echo "File $main_c_file created."
fi

create_file "Makefile" << 'EOF'
# Define the target name and build directory.
TARGET    := Project
BUILD_DIR := _build

.DEFAULT_GOAL := all

$(shell mkdir -p $(BUILD_DIR))

SRC := $(wildcard ./src/*.c)
ASM := $(wildcard ./src/*.s)

TOOLCHAIN := $(if $(GCC_PATH),$(GCC_PATH)/,)arm-none-eabi-

Q = $(if $(findstring $(space),$(1)),"$(1)",$(1))

CC = $(call Q,$(TOOLCHAIN)gcc)
LD = $(call Q,$(TOOLCHAIN)ld)
AS = $(call Q,$(TOOLCHAIN)gcc) -x assembler-with-cpp
CP = $(call Q,$(TOOLCHAIN)objcopy)
SZ = $(call Q,$(TOOLCHAIN)size)

space := $(subst ,, )

HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S

MCU = -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard
# The board uses an 8 MHz HSE crystal; override the vendor default (24 MHz)
# in system_stm32g4xx.c so any SystemCoreClockUpdate() call computes 170 MHz.
DEF = -DSTM32G431xx -DHSE_VALUE=8000000u
INC = -I./inc

FLG := $(MCU) $(DEF) $(INC)
FLG += -std=gnu11
FLG += -Wall -Werror -Wextra -Wpedantic
FLG += -fdata-sections -ffunction-sections -fverbose-asm
FLG += -MMD -MP
FLG += -fno-common

LDS := stm32g431cb_flash.ld
LIB := -lc -lm -lnosys
LDF := $(MCU) -specs=nano.specs -T$(LDS) $(LIB) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map
LDF += -Wl,--cref,--gc-sections,--print-memory-usage

OPT = -Os -g0 -DNDEBUG

ifeq ($(findstring -flto,$(OPT)), -flto)
  LST =
  LDF += -flto
else
  LST = -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst))
endif

FLAG_STAMP := $(BUILD_DIR)/.flags
$(FLAG_STAMP): Makefile
	@echo 'FLG=$(FLG)' >  $@.tmp
	@echo 'LDF=$(LDF)' >> $@.tmp
	@echo 'OPT=$(OPT)' >> $@.tmp
	@cmp -s $@.tmp $@ || mv $@.tmp $@
	@rm -f $@.tmp

JLINK_FLAGS = -openprj./stm32g431cb.jflash -open$(BUILD_DIR)/$(TARGET).hex -hide -auto -exit -jflashlog./jflash.log

ifeq ($(OS), Windows_NT)
    FLG += -D WIN32
    ifeq ($(PROCESSOR_ARCHITEW6432), AMD64)
        FLG += -D AMD64
    else
        ifeq ($(PROCESSOR_ARCHITECTURE), AMD64)
            FLG += -D AMD64
        endif
        ifeq ($(PROCESSOR_ARCHITECTURE), x86)
            FLG += -D IA32
        endif
    endif
    STLINK ?= ST-LINK_CLI.exe
    STLINK_FLAGS = -c SWD SWCLK=4000 UR -V -P $(BUILD_DIR)/$(TARGET).hex -Rst -Run
    JLINK ?= JFlash.Exe
else
    UNAME_S := $(shell uname -s)
    ifeq ($(UNAME_S), Linux)
        FLG += -D LINUX
    endif
    ifeq ($(UNAME_S), Darwin)
        FLG += -D OSX
    endif
    UNAME_P := $(shell uname -p)
    ifeq ($(UNAME_P), x86_64)
        FLG += -D AMD64
    endif
    ifneq ($(filter %86, $(UNAME_P)),)
        FLG += -D IA32
    endif
    ifneq ($(filter arm%, $(UNAME_P)),)
        FLG += -D ARM
    endif
    STLINK ?= st-flash
    STLINK_FLAGS = --reset --format ihex write $(BUILD_DIR)/$(TARGET).hex
    JLINK ?= JFlashExe
endif

GCC_INFO    := $(shell $(CC) -dumpfullversion 2>/dev/null | awk -F. '{print $$0, ($$1*10000+$$2*100+$$3>=120000)}')
GCC_VERSION := $(word 1,$(GCC_INFO))
GCC_GE_12   := $(word 2,$(GCC_INFO))

LD_INFO     := $(shell $(LD) --version 2>/dev/null | awk '/^GNU ld/ {match($$NF,/([0-9]+)\.([0-9]+)/,v); print v[0], (v[1]*100+v[2]>=239); exit}')
LD_VERSION  := $(word 1,$(LD_INFO))
LD_GE_2_39  := $(word 2,$(LD_INFO))

$(info using GCC $(GCC_VERSION), Binutils $(LD_VERSION))

ifneq ($(or $(filter 1,$(GCC_GE_12)),$(filter 1,$(LD_GE_2_39))),)
  LDF += -Wl,--no-warn-rwx-segments
endif

all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin

OBJ = $(addprefix $(BUILD_DIR)/,$(notdir $(SRC:.c=.o)))
vpath %.c $(sort $(dir $(SRC)))
OBJ += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM:.s=.o)))
vpath %.s $(sort $(dir $(ASM)))

DEP := $(OBJ:.o=.d)

$(BUILD_DIR)/%.o: %.c Makefile $(FLAG_STAMP) | $(BUILD_DIR)
	$(CC) -c $(FLG) $(OPT) -MF"$(@:%.o=%.d)" $(LST) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile $(FLAG_STAMP) | $(BUILD_DIR)
	$(AS) -c $(FLG) $(OPT) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJ) Makefile
	$(CC) $(OBJ) $(OPT) $(LDF) -o $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@

$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@

size: $(BUILD_DIR)/$(TARGET).elf
	$(SZ) $<

$(BUILD_DIR):
	mkdir -p $@

debug: OPT = -Og -g3 -gdwarf
debug: all

clean:
	-rm -fR $(BUILD_DIR)

.PHONY: clean all size

gccversion :
	@$(CC) --version

program: $(BUILD_DIR)/$(TARGET).hex
	$(STLINK) $(STLINK_FLAGS)

jprogram: $(BUILD_DIR)/$(TARGET).hex
	$(JLINK) $(JLINK_FLAGS)

-include $(DEP)
EOF

create_file "stm32g431cb_flash.ld" << 'EOF'
/* Linker script for STM32G431CBU6 (WeAct Studio G431 Core Board)
 *   128 KB Flash @ 0x08000000, 32 KB SRAM @ 0x20000000. */
ENTRY(Reset_Handler)

_estack = ORIGIN(RAM) + LENGTH(RAM);

_Min_Heap_Size  = 0x200;
_Min_Stack_Size = 0x400;

MEMORY
{
  FLASH (rx)  : ORIGIN = 0x08000000, LENGTH = 128K
  RAM   (rw)  : ORIGIN = 0x20000000, LENGTH = 32K
}

SECTIONS
{
  .isr_vector :
  {
    . = ALIGN(4);
    KEEP(*(.isr_vector))
    . = ALIGN(4);
  } >FLASH

  .text :
  {
    . = ALIGN(4);
    *(.text)
    *(.text*)
    *(.glue_7)
    *(.glue_7t)
    *(.eh_frame)

    KEEP(*(.init))
    KEEP(*(.fini))

    . = ALIGN(4);
    _etext = .;
  } >FLASH

  .rodata :
  {
    . = ALIGN(4);
    *(.rodata)
    *(.rodata*)
    . = ALIGN(4);
  } >FLASH

  .ARM.extab : { *(.ARM.extab* .gnu.linkonce.armextab.*) } >FLASH
  .ARM :
  {
    __exidx_start = .;
    *(.ARM.exidx*)
    __exidx_end = .;
  } >FLASH

  .preinit_array :
  {
    PROVIDE_HIDDEN(__preinit_array_start = .);
    KEEP(*(.preinit_array*))
    PROVIDE_HIDDEN(__preinit_array_end = .);
  } >FLASH

  .init_array :
  {
    PROVIDE_HIDDEN(__init_array_start = .);
    KEEP(*(SORT(.init_array.*)))
    KEEP(*(.init_array*))
    PROVIDE_HIDDEN(__init_array_end = .);
  } >FLASH

  .fini_array :
  {
    PROVIDE_HIDDEN(__fini_array_start = .);
    KEEP(*(SORT(.fini_array.*)))
    KEEP(*(.fini_array*))
    PROVIDE_HIDDEN(__fini_array_end = .);
  } >FLASH

  _sidata = LOADADDR(.data);

  .data :
  {
    . = ALIGN(4);
    _sdata = .;
    *(.data)
    *(.data*)
    . = ALIGN(4);
    _edata = .;
  } >RAM AT> FLASH

  .bss :
  {
    . = ALIGN(4);
    _sbss = .;
    __bss_start__ = _sbss;
    *(.bss)
    *(.bss*)
    *(COMMON)
    . = ALIGN(4);
    _ebss = .;
    __bss_end__ = _ebss;
  } >RAM

  ._user_heap_stack :
  {
    . = ALIGN(8);
    PROVIDE(end = .);
    PROVIDE(_end = .);
    . = . + _Min_Heap_Size;
    . = . + _Min_Stack_Size;
    . = ALIGN(8);
  } >RAM

  ASSERT(_estack - _end >= _Min_Stack_Size,
    "RAM overflow: .data + .bss + stack exceeds 32 KB")
}
EOF

# --------------------------------------------------------------------------- #
#  Keil MDK-ARM project (Cortex-M4 + FPU). Single Debug target.                #
# --------------------------------------------------------------------------- #
create_file "MDK-ARM/Project.uvprojx" << 'UVEOF'
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="project_projx.xsd">

  <SchemaVersion>2.1</SchemaVersion>

  <Header>### uVision Project, (C) Keil Software</Header>

  <Targets>
    <Target>
      <TargetName>Debug</TargetName>
      <ToolsetNumber>0x4</ToolsetNumber>
      <ToolsetName>ARM-ADS</ToolsetName>
      <uAC6>1</uAC6>
      <TargetOption>
        <TargetCommonOption>
          <Device>STM32G431CBUx</Device>
          <Vendor>STMicroelectronics</Vendor>
          <Cpu>IRAM(0x20000000,0x00008000) IROM(0x08000000,0x00020000) CPUTYPE("Cortex-M4") FPU CLOCK(170000000) ELITTLE</Cpu>
          <FlashUtilSpec></FlashUtilSpec>
          <StartupFile></StartupFile>
          <FlashDriverDll></FlashDriverDll>
          <DeviceId></DeviceId>
          <RegisterFile></RegisterFile>
          <MemoryEnv></MemoryEnv>
          <Cmp></Cmp>
          <Asm></Asm>
          <Linker></Linker>
          <OHString></OHString>
          <InfinionOptionDll></InfinionOptionDll>
          <SLE66CMisc></SLE66CMisc>
          <SLE66AMisc></SLE66AMisc>
          <SLE66LinkerMisc></SLE66LinkerMisc>
          <SFDFile>..\STM32G431xx.svd</SFDFile>
          <bCustSvd>0</bCustSvd>
          <UseEnv>0</UseEnv>
          <BinPath></BinPath>
          <IncludePath></IncludePath>
          <LibPath></LibPath>
          <RegisterFilePath></RegisterFilePath>
          <DBRegisterFilePath></DBRegisterFilePath>
          <TargetStatus>
            <Error>0</Error>
            <ExitCodeStop>0</ExitCodeStop>
            <ButtonStop>0</ButtonStop>
            <NotGenerated>0</NotGenerated>
            <InvalidFlash>1</InvalidFlash>
          </TargetStatus>
          <OutputDirectory>.\Objects\</OutputDirectory>
          <OutputName>Project</OutputName>
          <CreateExecutable>1</CreateExecutable>
          <CreateLib>0</CreateLib>
          <CreateHexFile>1</CreateHexFile>
          <DebugInformation>1</DebugInformation>
          <BrowseInformation>0</BrowseInformation>
          <ListingPath>.\Listings\</ListingPath>
          <HexFormatSelection>1</HexFormatSelection>
          <Merge32K>0</Merge32K>
          <CreateBatchFile>0</CreateBatchFile>
          <BeforeCompile>
            <RunUserProg1>0</RunUserProg1>
            <RunUserProg2>0</RunUserProg2>
            <UserProg1Name></UserProg1Name>
            <UserProg2Name></UserProg2Name>
            <UserProg1Dos16Mode>0</UserProg1Dos16Mode>
            <UserProg2Dos16Mode>0</UserProg2Dos16Mode>
            <nStopU1X>0</nStopU1X>
            <nStopU2X>0</nStopU2X>
          </BeforeCompile>
          <BeforeMake>
            <RunUserProg1>0</RunUserProg1>
            <RunUserProg2>0</RunUserProg2>
            <UserProg1Name></UserProg1Name>
            <UserProg2Name></UserProg2Name>
            <UserProg1Dos16Mode>0</UserProg1Dos16Mode>
            <UserProg2Dos16Mode>0</UserProg2Dos16Mode>
            <nStopB1X>0</nStopB1X>
            <nStopB2X>0</nStopB2X>
          </BeforeMake>
          <AfterMake>
            <RunUserProg1>0</RunUserProg1>
            <RunUserProg2>0</RunUserProg2>
            <UserProg1Name></UserProg1Name>
            <UserProg2Name></UserProg2Name>
            <UserProg1Dos16Mode>0</UserProg1Dos16Mode>
            <UserProg2Dos16Mode>0</UserProg2Dos16Mode>
            <nStopA1X>0</nStopA1X>
            <nStopA2X>0</nStopA2X>
          </AfterMake>
          <SelectedForBatchBuild>0</SelectedForBatchBuild>
          <SVCSIdString></SVCSIdString>
        </TargetCommonOption>
        <CommonProperty>
          <UseCPPCompiler>0</UseCPPCompiler>
          <RVCTCodeConst>0</RVCTCodeConst>
          <RVCTZI>0</RVCTZI>
          <RVCTOtherData>0</RVCTOtherData>
          <ModuleSelection>0</ModuleSelection>
          <IncludeInBuild>1</IncludeInBuild>
          <AlwaysBuild>0</AlwaysBuild>
          <GenerateAssemblyFile>0</GenerateAssemblyFile>
          <AssembleAssemblyFile>0</AssembleAssemblyFile>
          <PublicsOnly>0</PublicsOnly>
          <StopOnExitCode>3</StopOnExitCode>
          <CustomArgument></CustomArgument>
          <IncludeLibraryModules></IncludeLibraryModules>
          <ComprImg>1</ComprImg>
        </CommonProperty>
        <DllOption>
          <SimDllName>SARMCM3.DLL</SimDllName>
          <SimDllArguments> -REMAP </SimDllArguments>
          <SimDlgDll>DARMCM1.DLL</SimDlgDll>
          <SimDlgDllArguments>-pCM4</SimDlgDllArguments>
          <TargetDllName>SARMCM3.DLL</TargetDllName>
          <TargetDllArguments> </TargetDllArguments>
          <TargetDlgDll>TARMCM1.DLL</TargetDlgDll>
          <TargetDlgDllArguments>-pCM4</TargetDlgDllArguments>
        </DllOption>
        <DebugOption>
          <OPTHX>
            <HexSelection>1</HexSelection>
            <HexRangeLowAddress>0</HexRangeLowAddress>
            <HexRangeHighAddress>0</HexRangeHighAddress>
            <HexOffset>0</HexOffset>
            <Oh166RecLen>16</Oh166RecLen>
          </OPTHX>
        </DebugOption>
        <Utilities>
          <Flash1>
            <UseTargetDll>1</UseTargetDll>
            <UseExternalTool>0</UseExternalTool>
            <RunIndependent>0</RunIndependent>
            <UpdateFlashBeforeDebugging>1</UpdateFlashBeforeDebugging>
            <Capability>1</Capability>
            <DriverSelection>4096</DriverSelection>
          </Flash1>
          <bUseTDR>1</bUseTDR>
          <Flash2>BIN\UL2CM3.DLL</Flash2>
          <Flash3>"" ()</Flash3>
          <Flash4></Flash4>
        </Utilities>
      </TargetOption>
      <DebugOpt>
        <SFDebuggerSet></SFDebuggerSet>
        <SFDll>..\STM32G431xx.svd</SFDll>
      </DebugOpt>
      <TraceOpt></TraceOpt>
      <TargetArmAds>
        <Cpu>CPUTYPE("Cortex-M4") CLOCK(170000000) ELITTLE</Cpu>
        <uocRom>0</uocRom>
        <uocRam>0</uocRam>
        <hadIROM>1</hadIROM>
        <hadIRAM>1</hadIRAM>
        <hadXRAM>0</hadXRAM>
        <uocXRam>0</uocXRam>
        <RvdsVP>0</RvdsVP>
        <RvdsMve>0</RvdsMve>
        <RvdsCdeCp>0</RvdsCdeCp>
        <hadIRAM2>0</hadIRAM2>
        <hadIROM2>0</hadIROM2>
        <StupSel>8</StupSel>
        <useUlib>1</useUlib>
        <EndSel>0</EndSel>
        <uLtcg>0</uLtcg>
        <nSecure>0</nSecure>
        <RoSelD>3</RoSelD>
        <RwSelD>3</RwSelD>
        <CodeSel>0</CodeSel>
        <OptFeed>0</OptFeed>
        <NoZi1>0</NoZi1>
        <NoZi2>0</NoZi2>
        <NoZi3>0</NoZi3>
        <NoZi4>0</NoZi4>
        <NoZi5>0</NoZi5>
        <Ro1Chk>1</Ro1Chk>
        <Ro2Chk>0</Ro2Chk>
        <Ro3Chk>0</Ro3Chk>
        <Ir1Chk>1</Ir1Chk>
        <Ir2Chk>0</Ir2Chk>
        <Ra1Chk>0</Ra1Chk>
        <Ra2Chk>0</Ra2Chk>
        <Ra3Chk>0</Ra3Chk>
        <Im1Chk>1</Im1Chk>
        <Im2Chk>0</Im2Chk>
        <OnChipMemories>
          <Ocm1>
            <Type>0</Type>
            <StartAddress>0x0</StartAddress>
            <Size>0x0</Size>
          </Ocm1>
          <Ocm2>
            <Type>0</Type>
            <StartAddress>0x0</StartAddress>
            <Size>0x0</Size>
          </Ocm2>
          <Ocm3>
            <Type>0</Type>
            <StartAddress>0x0</StartAddress>
            <Size>0x0</Size>
          </Ocm3>
          <Ocm4>
            <Type>0</Type>
            <StartAddress>0x0</StartAddress>
            <Size>0x0</Size>
          </Ocm4>
          <Ocm5>
            <Type>0</Type>
            <StartAddress>0x0</StartAddress>
            <Size>0x0</Size>
          </Ocm5>
          <Ocm6>
            <Type>0</Type>
            <StartAddress>0x0</StartAddress>
            <Size>0x0</Size>
          </Ocm6>
          <IRAM>
            <Type>0</Type>
            <StartAddress>0x20000000</StartAddress>
            <Size>0x8000</Size>
          </IRAM>
          <IROM>
            <Type>1</Type>
            <StartAddress>0x08000000</StartAddress>
            <Size>0x20000</Size>
          </IROM>
          <XRAM>
            <Type>0</Type>
            <StartAddress>0x0</StartAddress>
            <Size>0x0</Size>
          </XRAM>
          <OCR_RVCT1>
            <Type>1</Type>
            <StartAddress>0x0</StartAddress>
            <Size>0x0</Size>
          </OCR_RVCT1>
          <OCR_RVCT2>
            <Type>1</Type>
            <StartAddress>0x0</StartAddress>
            <Size>0x0</Size>
          </OCR_RVCT2>
          <OCR_RVCT3>
            <Type>1</Type>
            <StartAddress>0x0</StartAddress>
            <Size>0x0</Size>
          </OCR_RVCT3>
          <OCR_RVCT4>
            <Type>1</Type>
            <StartAddress>0x08000000</StartAddress>
            <Size>0x20000</Size>
          </OCR_RVCT4>
          <OCR_RVCT5>
            <Type>1</Type>
            <StartAddress>0x0</StartAddress>
            <Size>0x0</Size>
          </OCR_RVCT5>
          <OCR_RVCT6>
            <Type>0</Type>
            <StartAddress>0x0</StartAddress>
            <Size>0x0</Size>
          </OCR_RVCT6>
          <OCR_RVCT7>
            <Type>0</Type>
            <StartAddress>0x0</StartAddress>
            <Size>0x0</Size>
          </OCR_RVCT7>
          <OCR_RVCT8>
            <Type>0</Type>
            <StartAddress>0x0</StartAddress>
            <Size>0x0</Size>
          </OCR_RVCT8>
          <OCR_RVCT9>
            <Type>0</Type>
            <StartAddress>0x20000000</StartAddress>
            <Size>0x8000</Size>
          </OCR_RVCT9>
          <OCR_RVCT10>
            <Type>0</Type>
            <StartAddress>0x0</StartAddress>
            <Size>0x0</Size>
          </OCR_RVCT10>
        </OnChipMemories>
        <RvctStartVector></RvctStartVector>
        <ArmAdsMisc>
          <Cads>
            <interw>1</interw>
            <Optim>1</Optim>
            <oTime>0</oTime>
            <SplitLS>0</SplitLS>
            <OneElfS>1</OneElfS>
            <Strict>0</Strict>
            <EnumInt>0</EnumInt>
            <PlainCh>0</PlainCh>
            <Ropi>0</Ropi>
            <Rwpi>0</Rwpi>
            <wLevel>2</wLevel>
            <uThumb>0</uThumb>
            <uSurpInc>0</uSurpInc>
            <uC99>0</uC99>
            <uGnu>0</uGnu>
            <useXO>0</useXO>
            <v6Lang>6</v6Lang>
            <v6LangP>9</v6LangP>
            <vShortEn>1</vShortEn>
            <vShortWch>1</vShortWch>
            <v6Lto>0</v6Lto>
            <v6WtE>1</v6WtE>
            <v6Rtti>0</v6Rtti>
            <VariousControls>
              <MiscControls>-Wpedantic -Wextra</MiscControls>
              <Define>STM32G431xx DEBUG</Define>
              <Undefine></Undefine>
              <IncludePath>../inc</IncludePath>
            </VariousControls>
          </Cads>
          <Aads>
            <interw>1</interw>
            <Ropi>0</Ropi>
            <Rwpi>0</Rwpi>
            <thumb>0</thumb>
            <SplitLS>0</SplitLS>
            <SwStkChk>0</SwStkChk>
            <NoWarn>0</NoWarn>
            <uSurpInc>0</uSurpInc>
            <useXO>0</useXO>
            <ClangAsOpt>1</ClangAsOpt>
            <VariousControls>
              <MiscControls></MiscControls>
              <Define></Define>
              <Undefine></Undefine>
              <IncludePath></IncludePath>
            </VariousControls>
          </Aads>
          <LDads>
            <umfTarg>1</umfTarg>
            <Ropi>0</Ropi>
            <Rwpi>0</Rwpi>
            <noStLib>0</noStLib>
            <RepFail>1</RepFail>
            <useFile>0</useFile>
            <TextAddressRange>0x08000000</TextAddressRange>
            <DataAddressRange>0x20000000</DataAddressRange>
            <pXoBase></pXoBase>
            <ScatterFile></ScatterFile>
            <IncludeLibs></IncludeLibs>
            <IncludeLibsPath></IncludeLibsPath>
            <Misc></Misc>
            <LinkerInputFile></LinkerInputFile>
            <DisabledWarnings></DisabledWarnings>
          </LDads>
        </ArmAdsMisc>
        <Cads>
          <interw>1</interw>
          <Optim>1</Optim>
          <oTime>0</oTime>
          <SplitLS>0</SplitLS>
          <OneElfS>1</OneElfS>
          <Strict>0</Strict>
          <EnumInt>0</EnumInt>
          <PlainCh>0</PlainCh>
          <Ropi>0</Ropi>
          <Rwpi>0</Rwpi>
          <wLevel>2</wLevel>
          <uThumb>0</uThumb>
          <uSurpInc>0</uSurpInc>
          <uC99>0</uC99>
          <uGnu>0</uGnu>
          <useXO>0</useXO>
          <v6Lang>6</v6Lang>
          <v6LangP>9</v6LangP>
          <vShortEn>1</vShortEn>
          <vShortWch>1</vShortWch>
          <v6Lto>0</v6Lto>
          <v6WtE>1</v6WtE>
          <v6Rtti>0</v6Rtti>
          <VariousControls>
            <MiscControls>-Wpedantic -Wextra</MiscControls>
            <Define>STM32G431xx DEBUG</Define>
            <Undefine></Undefine>
            <IncludePath>../inc</IncludePath>
          </VariousControls>
        </Cads>
        <Aads>
          <interw>1</interw>
          <Ropi>0</Ropi>
          <Rwpi>0</Rwpi>
          <thumb>0</thumb>
          <SplitLS>0</SplitLS>
          <SwStkChk>0</SwStkChk>
          <NoWarn>0</NoWarn>
          <uSurpInc>0</uSurpInc>
          <useXO>0</useXO>
          <ClangAsOpt>1</ClangAsOpt>
          <VariousControls>
            <MiscControls></MiscControls>
            <Define></Define>
            <Undefine></Undefine>
            <IncludePath></IncludePath>
          </VariousControls>
        </Aads>
        <LDads>
          <umfTarg>1</umfTarg>
          <Ropi>0</Ropi>
          <Rwpi>0</Rwpi>
          <noStLib>0</noStLib>
          <RepFail>1</RepFail>
          <useFile>0</useFile>
          <TextAddressRange>0x08000000</TextAddressRange>
          <DataAddressRange>0x20000000</DataAddressRange>
          <pXoBase></pXoBase>
          <ScatterFile></ScatterFile>
          <IncludeLibs></IncludeLibs>
          <IncludeLibsPath></IncludeLibsPath>
          <Misc></Misc>
          <LinkerInputFile></LinkerInputFile>
          <DisabledWarnings></DisabledWarnings>
        </LDads>
      </TargetArmAds>
      <Groups>
        <Group>
          <GroupName>src</GroupName>
          <Files>
            <File>
              <FileName>main.c</FileName>
              <FileType>1</FileType>
              <FilePath>..\src\main.c</FilePath>
            </File>
            <File>
              <FileName>startup_stm32g431xx.s</FileName>
              <FileType>2</FileType>
              <FilePath>..\MDK-ARM\startup_stm32g431xx.s</FilePath>
            </File>
            <File>
              <FileName>system_stm32g4xx.c</FileName>
              <FileType>1</FileType>
              <FilePath>..\src\system_stm32g4xx.c</FilePath>
            </File>
          </Files>
        </Group>
      </Groups>
    </Target>
  </Targets>

  <RTE>
    <apis/>
    <components/>
    <files/>
  </RTE>

  <LayerInfo>
    <Layers>
      <Layer>
        <LayName>Project</LayName>
        <LayPrjMark>1</LayPrjMark>
      </Layer>
    </Layers>
  </LayerInfo>

</Project>
UVEOF

# SEGGER Ozone debugger script (J-Link)
create_file "project.jdebug" << 'EOF'
void OnProjectLoad (void) {
  Project.AddPathSubstitute (".", "$(ProjectDir)");
  Project.SetDevice ("STM32G431CB");
  Project.SetHostIF ("USB", "");
  Project.SetTargetIF ("SWD");
  Project.SetTIFSpeed ("4 MHz");
  Project.AddSvdFile ("$(InstallDir)/Config/CPU/Cortex-M4.svd");
  Project.AddSvdFile ("$(InstallDir)/Config/Peripherals/ARMv7M.svd");
  Project.AddSvdFile ("$(ProjectDir)/STM32G431xx.svd");
  File.Open ("$(ProjectDir)/_build/Project.elf");
}

void AfterTargetReset (void) {
  _SetupTarget();
}

void AfterTargetDownload (void) {
  _SetupTarget();
}

void _SetupTarget(void) {
  unsigned int SP;
  unsigned int PC;
  unsigned int VectorTableAddr;

  VectorTableAddr = Elf.GetBaseAddr();
  SP = Target.ReadU32(VectorTableAddr);
  if (SP != 0xFFFFFFFF) {
    Target.SetReg("SP", SP);
  }
  PC = Elf.GetEntryPointPC();
  if (PC != 0xFFFFFFFF) {
    Target.SetReg("PC", PC);
  } else {
    Util.Error("Project script error: failed to set up entry point PC", 1);
  }
}
EOF

# SEGGER J-Flash project
create_file "stm32g431cb.jflash" << 'EOF'
  AppVersion =
  FileVersion = 2
[GENERAL]
  aATEModuleSel[24] = 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
  ConnectMode = 0
  CurrentFile = ""
  DataFileSAddr = 0x00000000
  GUIMode = 0
  HostName = ""
  TargetIF = 1
  USBPort = 0
  USBSerialNo = 0x00000000
  UseATEModuleSelection = 0
[JTAG]
  IRLen = 0
  MultipleTargets = 0
  NumDevices = 0
  Speed0 = 4000
  Speed1 = 4000
  TAP_Number = 0
  UseAdaptive0 = 0
  UseAdaptive1 = 0
  UseMaxSpeed0 = 0
  UseMaxSpeed1 = 0
[CPU]
  NumInitSteps = 1
  InitStep0_Action = "Reset"
  InitStep0_Value0 = 0x00000000
  InitStep0_Value1 = 0x00000000
  InitStep0_Comment = "Reset and halt target"
  NumExitSteps = 0
  UseScriptFile = 0
  ScriptFile = ""
  UseRAM = 1
  RAMAddr = 0x20000000
  RAMSize = 0x00008000
  CheckCoreID = 1
  CoreID = 0x0BA00477
  CoreIDMask = 0x0F000FFF
  UseAutoSpeed = 0x00000001
  ClockSpeed = 0x00000000
  EndianMode = 0
  ChipName = "ST STM32G431CB"
[FLASH]
  aRangeSel[1] = 0-63
  BankName = "Internal flash"
  BankSelMode = 1
  BaseAddr = 0x08000000
  NumBanks = 1
[PRODUCTION]
  AutoPerformsDisconnect = 0
  AutoPerformsErase = 1
  AutoPerformsProgram = 1
  AutoPerformsSecure = 0
  AutoPerformsStartApp = 0
  AutoPerformsUnsecure = 0
  AutoPerformsVerify = 1
  EnableFixedVTref = 0
  EnableTargetPower = 0
  EraseType = 1
  FixedVTref = 0x00000CE4
  MonitorVTref = 0
  MonitorVTrefMax = 0x0000157C
  MonitorVTrefMin = 0x000003E8
  OverrideTimeouts = 0
  ProgramSN = 0
  SerialFile = ""
  SNAddr = 0x00000000
  SNInc = 0x00000001
  SNLen = 0x00000004
  SNListFile = ""
  SNValue = 0x00000001
  StartAppType = 0
  TargetPowerDelay = 0x00000014
  TimeoutErase = 0x00003A98
  TimeoutProgram = 0x00002710
  TimeoutVerify = 0x00002710
  VerifyType = 1
[PERFORMANCE]
  DisableSkipBlankDataOnProgram = 0x00000000
  PerfromBlankCheckPriorEraseChip = 0x00000001
  PerfromBlankCheckPriorEraseSelectedSectors = 0x00000001
EOF

# SEGGER Embedded Studio project (SES bundles its own startup; uses ./src/*.c)
create_file "project.emProject" << 'EOF'
<!DOCTYPE CrossStudio_Project_File>
<solution Name="project" target="8" version="2">
  <configuration Name="Debug" inherited_configurations="Internal;Debug" />
  <configuration Name="Internal" Platform="ARM" hidden="Yes" />
  <configuration Name="Release" inherited_configurations="Internal;Release" />
  <project Name="G431CB">
    <configuration
      Name="Common"
      WARNING_LEVEL="4 (All)"
      arm_assembler_variant="SEGGER"
      arm_compiler_variant="SEGGER"
      arm_core_type="Cortex-M4"
      arm_endian="Little"
      arm_fpu_variant="VFPv4-D16"
      arm_fpu_abi="Hard"
      arm_linker_treat_warnings_as_errors="Yes"
      arm_linker_variant="SEGGER"
      arm_target_device_name="STM32G431CB"
      arm_target_interface_type="SWD"
      c_preprocessor_definitions="STM32G431xx"
      c_user_include_directories="./inc"
      debug_svd_file="$(ProjectDir)/STM32G431xx.svd"
      debug_start_from_entry_point_symbol="No"
      debug_target_connection="J-Link"
      gcc_c_language_standard="gnu17"
      gcc_enable_all_warnings="Yes"
      gcc_strict_prototypes_warning="Yes"
      gcc_uninitialized_variables_warning="Yes"
      gcc_unused_variable_warning="Yes"
      link_linker_script_file="$(StudioDir)/samples/SEGGER_Flash.icf"
      link_map_file="Detailed"
      linker_log_file="Yes"
      linker_output_format="hex"
      linker_section_placements_segments="FLASH1 RX 0x08000000 0x00020000;RAM1 RWX 0x20000000 0x00008000;"
      project_type="Executable" />
    <configuration
      Name="Debug"
      gcc_debugging_level="Level 3"
      gcc_dwarf_version="dwarf-5" />
    <configuration
      LIBRARY_IO_TYPE="SEMIHOST (host-formatted)"
      Name="Internal" />
    <configuration
      Name="Release"
      c_preprocessor_definitions="NDEBUG"
      gcc_debugging_level="None"
      gcc_dwarf_version="None"
      gcc_optimization_level="Level 2 for size"
      gcc_strip_symbols="Yes"
      link_dedupe_code="Yes"
      link_dedupe_data="Yes"
      link_inline="Yes"
      linker_strip_debug_information="Yes" />
    <folder Name="app">
      <file file_name="./src/main.c" />
    </folder>
    <folder Name="startup">
      <file file_name="$(StudioDir)/samples/Cortex_M_Startup.s" />
      <file file_name="$(StudioDir)/samples/SEGGER_THUMB_Startup.s" />
      <file file_name="./src/system_stm32g4xx.c" />
    </folder>
  </project>
</solution>
EOF

# --------------------------------------------------------------------------- #
#  Download vendor CMSIS files (cached for re-runs).                           #
# --------------------------------------------------------------------------- #
fname1=("system_stm32g4xx.c" "startup_stm32g431xx.s")
fname2=("system_stm32g4xx.h" "stm32g4xx.h" "stm32g431xx.h")
fname3=("core_cm4.h" "cmsis_compiler.h" "cmsis_gcc.h" "cmsis_armclang.h" "cmsis_iccarm.h" "cmsis_version.h" "cmsis_armcc.h" "mpu_armv7.h")

raw_github="https://raw.githubusercontent.com/"

url1="${raw_github}STMicroelectronics/cmsis-device-g4/refs/heads/master"
url2="${raw_github}ARM-software/CMSIS_5/refs/heads/master/CMSIS/Core/Include/"
url3="${raw_github}cmsis-svd/cmsis-svd-data/refs/heads/main/data/STMicro/STM32G431xx.svd"

# Function to check if a file exists and download it if it doesn't
download_file() {
    local url="$1"
    local dest="$2"

    if [ ! -f "$dest" ]; then
        if curl -fsSL "$url" | tr -cd '\11\12\15\40-\176' > "$dest"; then
            if [ -s "$dest" ]; then  # Check file is not empty
                ((++op_counter))
                echo "File $dest downloaded."
            else
                echo "Error: Downloaded file $dest is empty" >&2
                rm -f "$dest"
                return 1
            fi
        else
            echo "Error: Failed to download $url" >&2
            return 1
        fi
    fi
}

download_file "${url1}/Source/Templates/${fname1[0]}" "${directories[1]}/${fname1[0]}"
download_file "${url1}/Source/Templates/gcc/${fname1[1]}" "${directories[1]}/${fname1[1]}"
download_file "${url1}/Source/Templates/arm/${fname1[1]}" "${directories[2]}/${fname1[1]}"
download_file "${url3}" "STM32G431xx.svd"

# Download files
for filename in "${fname2[@]}"
do
  download_file "${url1}/Include/${filename}" "${directories[0]}/${filename}"
done

for filename in "${fname3[@]}"
do
  download_file "${url2}${filename}" "${directories[0]}/${filename}"
done

# --------------------------------------------------------------------------- #
#  README                                                                      #
# --------------------------------------------------------------------------- #
create_file "README.md" << 'EOF'
# STM32G431CB Demo

Bare-metal example for the **STM32G431CBU6** (WeAct Studio STM32G431 Core Board),
generated by `g431cb_demo.sh`. It demonstrates a **170 MHz** clock (the rated
maximum for the G4, a Cortex-M4F part) and a simple **LED** blink on **PC6**
(active HIGH) — all using only CMSIS, no HAL.

The example reuses the best practices of the other demos: `stm32cgen` produces
`main.h` (clock + SysTick + init order) and `gpio.h` (PC6 output), while `rcc.h`
is a hand-written, header-only G4 clock/PLL/flash configuration.

---

## What the script does

`g431cb_demo.sh` is a self-contained project generator. Running it:

1. Creates the directory tree (`inc/`, `src/`, `MDK-ARM/`).
2. Generates the CMSIS-based configuration headers with `stm32cgen`:
   - `inc/main.h` — top-level config (clock, SysTick, init order) and the
     `init()` sequence (`init_rcc` -> `init_gpio` -> `init_systick`).
   - `inc/gpio.h` — `init_gpio()` configuring PC6 as a high-speed output using
     the G4 register bit naming (`GPIO_MODER_MODE*`, `GPIO_OSPEEDR_OSPEED*`).
   - `inc/rcc.h` — `init_rcc()` / `configure_flash()`: the PLL factor bits are
     wired directly for 170 MHz, with the correct G4 voltage-scaling sequence.
3. Writes `src/main.c` (PC6 blink off a 1 ms SysTick time base), the linker
   script, the Makefile and the debugger/IDE configurations.
4. Downloads the vendor CMSIS files (device header, startup, system init) and
   the SVD description from upstream sources (cached for re-runs).
5. Builds the project with `make debug` to verify everything is consistent.

All downloaded files are cached — re-running the script skips what already
exists and only rebuilds.

---

## Project structure

```
g431cb_demo/
├── README.md                 # this file
├── Makefile                  # GNU make build (arm-none-eabi-gcc)
├── STM32G431xx.svd           # peripheral description (shared by MDK/Ozone/SES)
├── project.emProject         # SEGGER Embedded Studio project
├── project.jdebug            # Ozone debugger script
├── stm32g431cb.jflash        # J-Link flash project
├── inc/
│   ├── main.h                # configuration + init() sequence
│   ├── rcc.h                 # init_rcc() / clock + PLL + flash configuration
│   ├── gpio.h                # init_gpio() + GPIO macros
│   ├── stm32g431xx.h         # CMSIS device header (downloaded)
│   ├── system_stm32g4xx.h
│   └── ...                   # other CMSIS/core headers
├── src/
│   ├── main.c                # application: PC6 LED blink
│   ├── system_stm32g4xx.c    # SystemInit() (clock configured in init_rcc)
│   └── startup_stm32g431xx.s # GCC startup (for the Make build)
├── MDK-ARM/
│   ├── Project.uvprojx       # Keil MDK-ARM project (Debug)
│   └── startup_stm32g431xx.s # ARM/Keil assembly startup (for MDK)
└── _build/                   # make output: Project.elf / .hex / .bin / .map
```

> The SVD file lives at the demo root so it can be shared by all the debugger
> configs: MDK via `<SFDFile>..\STM32G431xx.svd</SFDFile>`, Ozone via
> `$(ProjectDir)/STM32G431xx.svd`, and SES via
> `debug_svd_file="$(ProjectDir)/STM32G431xx.svd"`.

---

## Clock — 170 MHz

The G431 is a Cortex-M4F part rated up to **170 MHz**. `main.h` sets
`HCLK = 170`; `rcc.h` implements:

| Stage        | Value      | Result                |
|--------------|------------|-----------------------|
| HSE          | 8 MHz      | WeAct-style G431 crystal |
| PLLM         | 2          | VCO in = 4 MHz        |
| PLLN         | 85         | VCO = 340 MHz         |
| PLLR         | 2          | PLL = 170 MHz          |
| AHB (HPRE)   | /1         | HCLK = 170 MHz        |
| APB1 (PPRE1) | /2         | PCLK1 = 85 MHz        |
| APB2 (PPRE2) | /2         | PCLK2 = 85 MHz        |

### Verified 170 MHz

`configure_flash()` performs the correct G4 power sequence before the clock
switch: it enables the PWR clock, selects **regulator Range 1** and **clears
`PWR_CR5.R1MODE`** (boost mode, required to run the core above 150 MHz), then
programs the flash with **4 wait states** plus prefetch and both caches. The PLL
factor bits in `rcc.h` are written directly for the 170 MHz target. `init_rcc()`
stores `SystemCoreClock = 170000000u`, which the 1 ms SysTick in `main.h` uses.

> Note: the G4 is a single-PLL part (like the F4), so the clock tree is
> `HSE -> PLL (M/N/R) -> SYSCLK`. Unlike the G0, the GPIO banks live on
> `AHB2` and the flash needs wait states even at low frequencies.

---

## GPIO

- **LED — PC6**, active **HIGH** (pin HIGH = LED on), high-speed push-pull output.

`gpio.h` is generated by `stm32cgen` (`GPIOC`) using the analog-by-default XOR
scheme, adapted to the G4 register bit naming (`GPIO_MODER_MODE6`,
`GPIO_OSPEEDR_OSPEED6`, ...). `rcc.h` enables the `GPIOC` clock (AHB2) before
`init_gpio()` runs.

---

## Main loop

`src/main.c` runs the standard `for (init(); process(); idle());` loop with a
1 kHz SysTick (IRQ mode so `uptime()` advances):

```c
uint64_t now = uptime();
if ((now - last_toggle) >= 250u) {   /* toggle every 250 ms -> ~2 Hz */
  last_toggle = now;
  if (led_on) GPIOC->BSRR = GPIO_BSRR_BR6;  /* LED off */
  else        GPIOC->BSRR = GPIO_BSRR_BS6;  /* LED on  */
}
```

---

## Building

### GNU Make (arm-none-eabi-gcc)

```sh
bash ./g431cb_demo.sh  # generate + build (debug target)
make            # minimal build -> _build/Project.elf (+ .hex, .bin)
make debug      # debug build (-Og -g3 -gdwarf)
make size       # print ELF section sizes
make program    # flash via ST-Link
make jprogram   # flash via J-Link (J-Flash)
make clean      # remove build output
```

### Keil MDK-ARM

Open `MDK-ARM/Project.uvprojx` in uVision, or build headlessly:

```sh
UV4.exe -b MDK-ARM/Project.uvprojx -t "Debug"
```

The MDK project references the SVD from the demo root, so the peripheral
windows are populated during debugging without installing any device pack.

### SEGGER Embedded Studio

Open `project.emProject`, or build headlessly with `emBuild`:

```sh
emBuild.exe -config Debug project.emProject
```

SES uses its own built-in startup files; the external `startup_stm32g431xx.s`
is only consumed by the MDK project.

---

## Flashing and debugging

Connect a J-Link (or an external ST-Link) to the board: SWDIO -> PA13,
SWCLK -> PA14, GND -> GND, 3.3V -> 3.3V.

- **Ozone** (J-Link): open `project.jdebug`; it loads `_build/Project.elf`
  and the shared SVD.
- **J-Flash / J-Link Commander**: `make jprogram` uses `stm32g431cb.jflash`
  (device `STM32G431CB`).
- **ST-Link CLI** (Windows):
  ```sh
  ST-LINK_CLI.exe -c SWD SWCLK=4000 UR -P _build/Project.hex -Rst -Run
  ```
- **MDK / SES**: use the integrated flash + debug buttons.

---

## Configuration knobs

The main tunables live at the top of `inc/main.h`:

| Macro                 | Default | Meaning                          |
|-----------------------|---------|----------------------------------|
| `HCLK`                | `170`   | System clock in MHz (8-170)      |
| `SYSTICK_CLOCK_SOURCE`| `0`     | 0 = HCLK/8, 1 = HCLK             |
| `SYSTICK_ENABLE`      | `YES`   | enable SysTick                   |
| `SYSTICK_IRQ_ENABLE`  | `YES`   | IRQ vs polling mode              |

To change the LED pin, edit the `GPIOC_MODE` define in `inc/gpio.h` (or the
`stm32cgen` invocation in the `.sh` script); the `GPIOC` clock-enable bit is
handled by `rcc.h`.

---

## References

- STM32G431 datasheet (DS12989), RM0440 (STM32G4 reference manual)
- [stm32codegen](https://github.com/a5021/stm32codegen) — generates
  `main.h` / `gpio.h` from the command line
- [BluePill_Project_Generator](https://github.com/a5021/BluePill_Project_Generator)
  — source of the GPIO macros and the overall structure
EOF

echo -e "\nBuilding sources..\n"

if make debug; then
    echo ""
    echo "====================================="
    echo "Project setup complete!"
    echo "  Operations performed: $op_counter"
    echo "  Project directory: $base_dir"
    echo "  Build: SUCCESS"
    echo "====================================="
    echo ""
else
    echo ""
    echo "====================================="
    echo "Build FAILED!"
    echo "  Check error messages above"
    echo "====================================="
    echo ""
    exit 1
fi

press_any_key
